// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
 // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // Manually defined sidebar for your technical writing portfolio
  technicalWritingPortfolioSidebar: [
    {
      type: 'category',
      label: 'Technical Writing Portfolio',
      items: [
        {
          type: 'category',
          label: 'User Guide Samples',
          items: [
            'technical-writing-portfolio/user-guide-samples/everytrack-concept-sample', // Corrected path
            'technical-writing-portfolio/user-guide-samples/everytrack-user-guide-task-based', // Corrected path
            'technical-writing-portfolio/user-guide-samples/connecting-whatsapp-to-omnichat', // Corrected path
          ],
        },
        {
          type: 'category',
          label: 'Technical Summaries',
          items: [
            'technical-writing-portfolio/technical-summaries/madds-architectural-tech-summary', // Corrected path
          ],
        },
        {
          type: 'category',
          label: 'API Documentation',
          items: [
            'technical-writing-portfolio/api-documentation/connect-api',
            'technical-writing-portfolio/api-documentation/pet-store-api'
          ],
        },
      ],
    },
  ],
};

export default sidebars;
